insert into public.publications (title, slug, kind, status_label, year, abstract, keywords, is_public, published_at)
values
('Virtual and Narrative Identity in the Age of AI: Ethical and Epistemological Perspectives','virtual-narrative-identity-ai','research_essay','Research essay','2026','Examines how AI systems reshape virtual and narrative identity through algorithmic co-authorship, with particular attention to authenticity, epistemic legitimacy, and the right to retain authorship over one’s self-narration.',array['narrative identity','AI ethics','algorithmic co-authorship'],true,now()),
('Epistemic Risk Surfaces in Large Language Models','epistemic-risk-surfaces-llms','working_paper','Working paper','2025–2026','Develops a taxonomy of epistemic failure in large language models, distinguishing confident error, synthetic coherence, uncertainty compression, and context-sensitive reliability collapse.',array['epistemic risk','LLM','reliability'],true,now()),
('Linguistic Symbolism and Meaning Compression in Machine Learning','linguistic-symbolism-meaning-compression','working_paper','Working paper','2025–2026','Explores the gap between linguistic fluency and semantic grounding by examining how symbolic structures are compressed in representation learning.',array['meaning','grounding','philosophy of language'],true,now()),
('Human Dignity Constraints for Autonomous Decision Systems','human-dignity-autonomous-systems','working_paper','Working paper','2025–2026','Argues that dignity-preserving design requires more than fairness metrics and must include contestability, recognition, meaningful human review, and access to remedy.',array['dignity','contestability','automated decisions'],true,now()),
('Ethical Architecture: Design Principles for Normative AI','ethical-architecture-normative-ai','working_paper','Working paper','2025–2026','Proposes design principles for embedding ethical constraints across models, interfaces, institutional roles, and remediation processes.',array['AI governance','design ethics','responsibility'],true,now()),
('Process Reliabilism and Machine Testimony','process-reliabilism-machine-testimony','working_paper','Working paper','2025–2026','Investigates whether AI-generated outputs can function as testimony and what forms of human, institutional, and technical warrant must accompany them.',array['testimony','reliabilism','epistemology'],true,now()),
('The Chinese Room Revisited: LLMs and Understanding','chinese-room-llm-understanding','working_paper','Working paper','2025–2026','Revisits the distinction between rule-governed symbol manipulation and understanding in the context of contemporary language models.',array['understanding','Chinese room','LLM'],true,now()),
('Democratic Oversight of AI Systems','democratic-oversight-ai-systems','working_paper','Working paper','2025–2026','Defends democratic rather than merely technocratic governance of AI systems, with attention to public reason, responsibility, institutional contestability, and legitimacy.',array['democracy','AI governance','public institutions'],true,now()),
('Guardrails in UX Safety: Designing Protective User Experiences','guardrails-ux-safety','manuscript','Manuscript','2026','A design-oriented ethics manuscript on protective user experiences, safety guardrails, and the normative role of interaction design.',array['UX safety','guardrails','design ethics'],true,now())
on conflict (slug) do nothing;
