-- Private archive candidates reconstructed from prior working-title records.
-- They are intentionally NOT public and do not claim peer review or publication.
insert into public.publications (title, slug, kind, status_label, year, abstract, keywords, is_public)
values
('AI & Human Dignity: Preserving Human Worth in the Age of Automation','ai-human-dignity-preserving-human-worth','working_paper','Working paper — verify source file','2025–2026','Archive candidate on human worth, autonomy, and the ethical constraints that should govern automated systems.',array['human dignity','automation','AI ethics'],false),
('Philosophy of Machine Agency: Autonomy and Responsibility in AI','philosophy-machine-agency-autonomy-responsibility','working_paper','Working paper — verify preprint record','2025–2026','Archive candidate on machine agency, autonomy, and the allocation of responsibility around AI systems.',array['machine agency','autonomy','responsibility'],false),
('Case Study: AI in Social Systems – Impact and Implementation','case-study-ai-social-systems','manuscript','Manuscript — verify source file','2025–2026','Archive candidate examining the institutional and social consequences of AI implementation.',array['social systems','implementation','AI ethics'],false),
('Epistemic Risks in AI','epistemic-risks-in-ai','working_paper','Working paper — verify source file','2025–2026','Archive candidate on reliability, uncertainty, authority, and the epistemic risks of AI-mediated claims.',array['epistemic risk','reliability','AI'],false),
('Human-in-the-Loop Autonomy','human-in-the-loop-autonomy','manuscript','Manuscript — verify source file','2025–2026','Archive candidate on meaningful human oversight and the limits of delegated autonomy.',array['human oversight','autonomy','governance'],false),
('Reversibility as a First-Class Safety Property','reversibility-first-class-safety-property','manuscript','Manuscript — verify source file','2025–2026','Archive candidate on reversibility, correction, rollback, and remedy as core properties of safe AI systems.',array['reversibility','safety','remedy'],false),
('Intent, Language, and Code','intent-language-code','manuscript','Manuscript — verify source file','2025–2026','Archive candidate on the translation of human intent into linguistic and computational instructions.',array['intent','language','code'],false),
('Fail-Safe AI for Cyber Defense','fail-safe-ai-cyber-defense','manuscript','Manuscript — verify source file','2025–2026','Archive candidate on fail-safe constraints and responsibility in AI-mediated cyber defense.',array['cyber defense','fail-safe','AI safety'],false),
('Autonomy Bounds','autonomy-bounds','manuscript','Manuscript — verify source file','2025–2026','Archive candidate on normative and operational limits for autonomous systems.',array['autonomy','constraints','AI governance'],false),
('From Policy to Guardrails','from-policy-to-guardrails','manuscript','Manuscript — verify source file','2025–2026','Archive candidate on translating ethical and institutional policy into enforceable system constraints.',array['policy','guardrails','governance'],false),
('Ethical Red Teaming for Autonomous Agents','ethical-red-teaming-autonomous-agents','manuscript','Manuscript — verify source file','2025–2026','Archive candidate on adversarial ethical testing for autonomous and agentic systems.',array['red teaming','autonomous agents','ethics'],false),
('Machine Agency and the Law','machine-agency-law','manuscript','Manuscript — verify source file','2025–2026','Archive candidate on legal and philosophical approaches to machine agency and responsibility.',array['machine agency','law','responsibility'],false),
('Cost-Aware LLM Serving','cost-aware-llm-serving','manuscript','Technical manuscript — verify source file','2025–2026','Archive candidate on resource-aware deployment and the operational trade-offs of large language model serving.',array['LLM serving','cost','infrastructure'],false)
on conflict (slug) do nothing;
